### ISSUE TITLE
这个APP是9月份那会儿完成的，当时想着找Android的工作（应届生），之后阴差阳错转到了java后端（系统的学习）。因此也很长时间没维护了，回复缓慢还请见谅

### ISSUE THREAD

**Issue by DuanJiaNing** [DuanJiaNing/Musicoco#11]

**Comment by KnIfER** [comment]
好像我错了。。

**Comment by helloworld10010** [comment]
应届生好厉害，本应届生惭愧不已

**Comment by KnIfER** [comment]
上了你的当！根本就不需要单独开一个进程。。
害得我写接口啊。。花了好久
\\\  
奇怪的是，即使xml里写上process名称(单独开一个进程)，通过ibinder调用service里的耗时方法，也会卡到ui，难道这是“跨进程阻塞”？  
此种情况下，通过intent notify调用，开process的主ui不会卡，不开的好像仍然会卡
\\\
大概这样后台播放的基本上不会使用分进程，因为这样，音频播放还好，视频后台播放几乎不可能，我用vlc做视频播放，vlc放在service里面，用于显示的view在ui里面，分进程会导致vlc永远无法直接访问ui里面的surface view，也就无法显示画面了。
